### ISSUE TITLE
about brainTS datasets

### ISSUE THREAD

**Issue by iaOlivia** [lpcccc-cv/MC-CDic#9]
Hi,
when I try to get access to The BrainTS datasets ,and it request to fill out the Google form but it not work anymore.
<img width="745" alt="image" src="https://github.com/lpcccc-cv/MC-CDic/assets/94520452/109c59be-9fe0-4cc6-b79a-82393ecbd465">
<img width="484" alt="image" src="https://github.com/lpcccc-cv/MC-CDic/assets/94520452/39f7eb24-7b33-4f79-964e-8616889b8d17">

**Comment by rookie108** [comment]
Hello, do I need to obtain permission through Submitted Jobs before I can download this dataset? How long do I need to wait? I haven't obtained permission yet. I look forward to your answer.
